import { Zhuyin } from '@/type/enums'

export default (keyword: string): Zhuyin => {
  switch (keyword) {
    case 'b':
      return Zhuyin.b
    case 'p':
      return Zhuyin.p
    case 'm':
      return Zhuyin.m
    case 'f':
      return Zhuyin.f
    case 'd':
      return Zhuyin.d
    case 't':
      return Zhuyin.t
    case 'n':
      return Zhuyin.n
    case 'l':
      return Zhuyin.l
    case 'g':
      return Zhuyin.g
    case 'k':
      return Zhuyin.k
    case 'h':
      return Zhuyin.h
    case 'j':
      return Zhuyin.j
    case 'q':
      return Zhuyin.q
    case 'x':
      return Zhuyin.x
    case 'zh':
      return Zhuyin.zh
    case 'ch':
      return Zhuyin.ch
    case 'sh':
      return Zhuyin.sh
    case 'r':
      return Zhuyin.r
    case 'z':
      return Zhuyin.z
    case 'c':
      return Zhuyin.c
    case 's':
      return Zhuyin.s
    case 'a':
      return Zhuyin.a
    case 'o':
      return Zhuyin.o
    case 'e':
      return Zhuyin.e
    case 'e2':
      return Zhuyin.e2
    case 'ai':
      return Zhuyin.ai
    case 'ei':
      return Zhuyin.ei
    case 'ao':
      return Zhuyin.ao
    case 'ou':
      return Zhuyin.ou
    case 'an':
      return Zhuyin.an
    case 'en':
      return Zhuyin.en
    case 'ang':
      return Zhuyin.ang
    case 'eng':
      return Zhuyin.eng
    case 'er':
      return Zhuyin.er
    case 'i':
      return Zhuyin.i
    case 'u':
      return Zhuyin.u
    case 'u2':
      return Zhuyin.u2
    case 'tone2':
      return Zhuyin.tone2
    case 'tone3':
      return Zhuyin.tone3
    case 'tone4':
      return Zhuyin.tone4
    case 'tone5':
      return Zhuyin.tone5
    case 'exclamation':
      return Zhuyin.exclamation
    case 'question':
      return Zhuyin.question
    case 'juhao':
      return Zhuyin.juhao
    case 'douhao':
      return Zhuyin.douhao
    default:
      return Zhuyin.error
  }
}
